services:
  - type: web
    name: meetingguard-backend
    env: node
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
